import SwiftUI
import PDFKit

class ExportService {
    static let shared = ExportService()
    
    @MainActor
    func generatePDF(flights: [[String: Any]]) -> URL? {
        let reportView = LogbookReportView(flights: flights)
        
        // A4 Landscape dimensions in points (72 points per inch)
        let a4Width: CGFloat = 841.89
        let a4Height: CGFloat = 595.28
        
        let renderer = ImageRenderer(content: reportView)
        renderer.proposedSize = .init(width: a4Width, height: a4Height)
        
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("AeroBook_Logbook_Export.pdf")
        
        renderer.render { size, context in
            var box = CGRect(origin: .zero, size: .init(width: a4Width, height: a4Height))
            
            guard let pdfContext = CGContext(url as CFURL, mediaBox: &box, nil) else { return }
            
            // Multi-page logic: Split flights into chunks that fit on a page
            let flightsPerPage = 15
            let totalPages = max(1, Int(ceil(Double(flights.count) / Double(flightsPerPage))))
            
            for pageIndex in 0..<totalPages {
                pdfContext.beginPage(mediaBox: &box)
                
                let start = pageIndex * flightsPerPage
                let end = min(start + flightsPerPage, flights.count)
                let pageFlights = Array(flights[start..<end])
                
                let pageView = LogbookReportView(flights: pageFlights, pageNumber: pageIndex + 1, totalPages: totalPages)
                let pageRenderer = ImageRenderer(content: pageView)
                pageRenderer.proposedSize = .init(width: a4Width, height: a4Height)
                
                pageRenderer.render { _, pageContext in
                    pageContext(pdfContext)
                }
                
                pdfContext.endPage()
            }
            
            pdfContext.closePDF()
        }
        
        return url
    }
}

struct LogbookReportView: View {
    let flights: [[String: Any]]
    var pageNumber: Int = 1
    var totalPages: Int = 1
    
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Header
            HStack {
                VStack(alignment: .leading) {
                    Text("PILOT LOGBOOK REPORT")
                        .font(.system(size: 24, weight: .black))
                    Text("Generated by AeroBook Local-First Logbook")
                        .font(.system(size: 10))
                        .foregroundStyle(.secondary)
                }
                Spacer()
                VStack(alignment: .trailing) {
                    Text("Page \(pageNumber) of \(totalPages)")
                        .font(.system(size: 10, weight: .bold))
                    Text(Date().formatted(date: .abbreviated, time: .omitted))
                        .font(.system(size: 10))
                }
            }
            .padding(.bottom, 10)
            
            // Table Header
            HStack(spacing: 0) {
                headerCell("DATE", width: 70)
                headerCell("AIRCRAFT", width: 100)
                headerCell("ROUTE", width: 120)
                headerCell("TOTAL", width: 50)
                headerCell("PIC", width: 50)
                headerCell("XC", width: 50)
                headerCell("NIGHT", width: 50)
                headerCell("INST", width: 50)
                headerCell("REMARKS", width: 250)
            }
            .background(Color.zinc900)
            
            // Table Rows
            VStack(spacing: 0) {
                ForEach(0..<flights.count, id: \.self) { index in
                    let flight = flights[index]
                    HStack(spacing: 0) {
                        dataCell(flight["date"] as? String ?? "", width: 70)
                        dataCell("\(flight["aircraft_type"] as? String ?? "") \(flight["aircraft_ident"] as? String ?? "")", width: 100)
                        dataCell(flight["route"] as? String ?? "", width: 120)
                        dataCell(String(format: "%.1f", flight["total_time"] as? Double ?? 0.0), width: 50)
                        dataCell(String(format: "%.1f", flight["pic"] as? Double ?? 0.0), width: 50)
                        dataCell(String(format: "%.1f", flight["cross_country"] as? Double ?? 0.0), width: 50)
                        dataCell(String(format: "%.1f", flight["night"] as? Double ?? 0.0), width: 50)
                        dataCell(String(format: "%.1f", flight["instrument_actual"] as? Double ?? 0.0), width: 50)
                        dataCell(flight["remarks"] as? String ?? "", width: 250, alignment: .leading)
                    }
                    .background(index % 2 == 0 ? Color.clear : Color.zinc50)
                    Divider()
                }
                
                // Fill empty rows to maintain page structure
                if flights.count < 15 {
                    ForEach(0..<(15 - flights.count), id: \.self) { _ in
                        HStack(spacing: 0) {
                            dataCell("", width: 70)
                            dataCell("", width: 100)
                            dataCell("", width: 120)
                            dataCell("", width: 50)
                            dataCell("", width: 50)
                            dataCell("", width: 50)
                            dataCell("", width: 50)
                            dataCell("", width: 50)
                            dataCell("", width: 250)
                        }
                        Divider()
                    }
                }
            }
            .border(Color.zinc200, width: 1)
            
            Spacer()
            
            // Footer
            HStack {
                Text("I certify that the entries in this logbook are true and correct.")
                    .font(.system(size: 8))
                    .italic()
                Spacer()
                VStack {
                    Divider().frame(width: 200)
                    Text("Pilot Signature")
                        .font(.system(size: 8))
                }
            }
        }
        .padding(40)
        .frame(width: 841.89, height: 595.28) // A4 Landscape
        .background(Color.white)
    }
    
    private func headerCell(_ text: String, width: CGFloat) -> some View {
        Text(text)
            .font(.system(size: 8, weight: .bold))
            .foregroundStyle(.white)
            .frame(width: width, height: 25)
            .border(Color.white.opacity(0.2), width: 0.5)
    }
    
    private func dataCell(_ text: String, width: CGFloat, alignment: Alignment = .center) -> some View {
        Text(text)
            .font(.system(size: 8))
            .padding(.horizontal, 4)
            .frame(width: width, height: 25, alignment: alignment)
            .border(Color.zinc200, width: 0.5)
    }
}
